# Generated by Django 5.0 on 2024-03-02 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('custom_topping', models.BooleanField(default=False)),
                ('custom_extra', models.BooleanField(default=False)),
                ('custom_size', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Monto_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montofinal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Monto_Inicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoinicial', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('caja_abierta', models.BooleanField(default=False)),
                ('total_ingresos', models.FloatField(default=0)),
                ('total_egresos', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameimpuesto', models.CharField(max_length=64)),
                ('montopagar', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Price_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_price', models.FloatField()),
                ('large_supp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prov_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.category')),
                ('base_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.price_list')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_price', models.FloatField()),
                ('is_current', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('extra', models.ManyToManyField(blank=True, to='orders.extra')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item_list')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.size')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('cart_id', models.ManyToManyField(to='orders.cart_list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.FloatField()),
                ('montototal', models.FloatField()),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.monto_inicial')),
                ('id_prov_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.prov_servicio')),
            ],
        ),
    ]
