# Generated by Django 5.0 on 2024-03-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='factura',
            field=models.CharField(max_length=64),
        ),
    ]
