# Generated by Django 5.0 on 2024-03-02 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_servicio_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='monto_final',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
